CREATE DATABASE IF NOT EXISTS trombinoscope;

USE trombinoscope;

CREATE TABLE IF NOT EXISTS eleve (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    pseudo VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);